services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.dev
    container_name: laravel_app_dev
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true