services:
  app:
    build:
      context: .
      target: prod
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app_prod
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - prod_net

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile.prod
    container_name: laravel_nginx_prod
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /etc/letsencrypt/archive/server1.fabriciolr.online:/etc/nginx/cert:ro
    depends_on:
      - app
    networks:
      - prod_net

networks:
  prod_net:
    driver: bridge
