FROM composer:latest

RUN apk add --no-cache npm

WORKDIR /app 

COPY . . 
RUN composer install --prefer-dist --no-dev --optimize-autoloader
RUN npm ci

RUN npm run build

RUN php artisan migrate

EXPOSE 8000

CMD ["php", "artisan", "serve", "--host=0.0.0.0"]