FROM php:8.4-fpm

RUN apt-get update && apt-get install -y libpq-dev unzip p7zip-full npm && docker-php-ext-install pdo pdo_pgsql pgsql

COPY --from=composer /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

COPY . .

CMD ["bash"]