FROM php:8.4-fpm

RUN apt-get update && apt-get install -y libpq-dev unzip p7zip-full npm && docker-php-ext-install pdo pdo_pgsql pgsql

COPY --from=composer /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

COPY . . 
RUN composer install
RUN npm install

EXPOSE 8000
EXPOSE 5173

CMD sh -c "php artisan serve --host=0.0.0.0 & npm run dev"