FROM composer:latest

RUN apk add --no-cache npm

WORKDIR /var/www

COPY . . 
RUN composer install
RUN npm ci

RUN php artisan key:generate
RUN php artisan migrate

EXPOSE 8000
EXPOSE 5173

CMD sh -c "php artisan serve --host=0.0.0.0 & npm run dev"