name: laravel-test

services:
  app:
    build:
      context: .
      target: test
      dockerfile: docker/php/Dockerfile
    entrypoint: []
    command: sh -c "touch .env && php artisan migrate --force && php artisan test"
    container_name: laravel_app_test
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: laravel_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
